# Generated by Django 3.0.2 on 2020-02-08 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('M&C', 'Mobiles & Computers'), ('MF', 'Men\\s Fashion'), ('WF', 'Women\\s Fashion'), ('H', 'Home'), ('B', 'Beauty')], default='H', max_length=100)),
                ('compositions', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('NONE', 'NONE'), ('S', 'small'), ('XS', 'extra small'), ('M', 'medium'), ('L', 'large'), ('XL', 'extra large')], default='NONE', max_length=50)),
                ('color', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('product_preview', models.ImageField(upload_to='static/assets/upload')),
                ('exclusive', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('NONE', 'NONE'), ('M', 'male'), ('F', 'female')], default='NONE', max_length=10)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='shop.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
