# Generated by Django 3.0.2 on 2020-01-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=100)),
                ('compositions', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('S', 'small'), ('XS', 'extra small'), ('M', 'medium'), ('L', 'large'), ('XL', 'extra large')], default='M', max_length=50)),
                ('color', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('product_preview', models.ImageField(upload_to='static/assets/upload')),
            ],
        ),
    ]
