# Generated by Django 3.0.2 on 2020-01-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobiles & Computers', 'Mobiles & Computers'), ('Men\\s Fashion', 'Men\\s Fashion'), ('Women\\s Fashion', 'Women\\s Fashion'), ('Home', 'Home'), ('Beauty', 'Beauty')], default='Home', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'small'), ('XS', 'extra small'), ('M', 'medium'), ('L', 'large'), ('XL', 'extra large'), ('NONE', 'NONE')], default='M', max_length=50),
        ),
    ]
