# Generated by Django 3.0.2 on 2020-01-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200118_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M&C', 'Mobiles & Computers'), ('MF', 'Men\\s Fashion'), ('WF', 'Women\\s Fashion'), ('H', 'Home'), ('B', 'Beauty')], default='H', max_length=100),
        ),
    ]
