# Generated by Django 3.0.2 on 2020-01-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200118_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
