# Generated by Django 3.0.2 on 2020-01-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_chart_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chart',
            new_name='Cart',
        ),
    ]
